#!/usr/bin/env bash

# Ensure changes are committed
if [[ $(git status -s) ]]; then
	echo "Error: Make sure working tree is clean before publishing"
	exit 1
fi

# Ensure user is publishing from master branch
if [[ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]]; then
	echo "Error: Can only publish from \"master\" branch"
	exit 1
fi

echo "Publishing..."

echo "Making sure local branch is up to date..."
git pull -q

echo "Creating temporary branch..."
git checkout -qb gh-pages
git pull -q origin gh-pages

echo "Generating static files..."
python freezer.py
local RET=$?
if [[ $RET -ne "0" ]]; then
    echo "Failed to build, have you setup the environment."
    exit 1
fi

echo "Moving static files..."
rsync -aq website/build/* .
rsync -aq website/other/* .

echo "Sending files to remote..."
git add --all
git commit -qm "Publish $(date -I)"
git push -q --set-upstream origin gh-pages

echo "Removing temporary branch..."
git checkout -q master
git branch -qd gh-pages

echo "Done publishing"
