#!/usr/bin/env bash

errors=0
# Ensure changes are committed
if [[ $(git status -s) ]]; then
	echo "Error: Make sure working tree is clean before publishing"
	errors=1
fi

# Make sure the person running this script has rsync
if ! type rsync &> /dev/null; then
    echo "Error: You have to install rsync to run this script"
	errors=1
fi

# Ensure user is publishing from master branch
if [[ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]]; then
	echo "Error: Can only publish from \"master\" branch"
	errors=1
fi

if [[ $errors -eq 1 ]]; then
    echo "Aborting due to error"
    exit 1
fi
echo "Publishing..."

echo "Making sure local branch is up to date..."
git pull
if [[ $(git status -s) ]]; then
	echo "Error: Fast-Forward failed. Fix any conflicts and publish again"
	exit 1
fi

echo "Creating temporary branch..."
git checkout -b gh-pages

echo "Generating static files..."
python freezer.py
if [[ $? -ne 0 ]]; then
	echo "Failed to build, have you setup the environment."
	echo "Removing temporary branch..."
	git checkout master
	git branch -D gh-pages
	exit 1
fi

echo "Moving static files..."
rsync -a website/build/* .
rsync -a website/other/* .

echo "Sending files to remote..."
git add --all
git commit -m "Publish $(date -I)" --no-gpg-sign
git push -f --set-upstream origin gh-pages

echo "Removing temporary branch..."
git checkout master
git branch -D gh-pages

echo "Done publishing"
