#!/usr/bin/env bash

if [[ $(git status -s) ]]; then
	echo "Make sure working tree is clean before publishing"
fi

echo "Publishing..."

git checkout -b gh-pages
git pull --ff-only origin gh-pages

python freezer.py
rsync -av website/build/* .

git add --all
git commit -m "Publish $(date -I)"
git push --set-upstream origin gh-pages

git checkout master
git branch -d gh-pages

echo "Done publishing"
